server:
  port: 8080

spring:
  application:
    name: ApiGateWay
  profiles:
    active:
      on-profile: prod
  security:
    user:
      name: admin
      password: admin
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: game-mng-service
          uri: lb://GAME-MNG-SERVICE
          predicates:
            - Path=/game-mng-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-mng-service/(?<segment>.*), /$\{segment}
        - id: ticket-sue-service
          uri: lb://TICKET-SUE-SERVICE
          predicates:
            - Path=/ticket-sue-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ticket-sue-service/(?<segment>.*), /$\{segment}
        - id: game-lotto645-service
          uri: lb://GAME-LOTTO645-SERVICE
          predicates:
            - Path=/game-lotto645-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-lotto645-service/(?<segment>.*), /$\{segment}
        - id: game-lotto649-service
          uri: lb://GAME-LOTTO649-SERVICE
          predicates:
            - Path=/game-lotto649-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-lotto649-service/(?<segment>.*), /$\{segment}
        - id: game-powerball-service
          uri: lb://GAME-POWERBALL-SERVICE
          predicates:
            - Path=/game-powerball-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-powerball-service/(?<segment>.*), /$\{segment}
        - id: openapi
          uri: http://cenlots2024-cenlots-api-service
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

info:
  app:
    name: Spring Cloud Gateway
    description: API 라우팅 및 보안, 모니터링/메트릭 등의 기능을 간단하고 효과적인 방법으로 제공
  swagger-ui: http://cenlots2024-cenlots-api-service/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

springdoc:
  swagger-ui:
  path: /swagger-ui.html

apigateway:
  host: https://cenlots2024-cenlots-api-service

eureka:
  instance:
    prefer-ip-address: true
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
  
