server:
  port: 8000

spring:
  application:
    name: ApiGateWay
  profiles:
    active:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: game-mng-service
          uri: lb://GAME-MNG-SERVICE
          predicates:
            - Path=/game-mng-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-mng-service/(?<segment>.*), /$\{segment}
        - id: ticket-sue-service
          uri: lb://TICKET-SUE-SERVICE
          predicates:
            - Path=/ticket-sue-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ticket-sue-service/(?<segment>.*), /$\{segment}
        - id: openapi
          uri: http://cenlots-api.cloit.dev:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

info:
  app:
    name: Spring Cloud Gateway
    description: API 라우팅 및 보안, 모니터링/메트릭 등의 기능을 간단하고 효과적인 방법으로 제공
  swagger-ui: http://cenlots-api.cloit.dev:8000/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

springdoc:
  swagger-ui:
  path: /swagger-ui.html

messages:
  directory: test # ${user.dir}/msa-attach-volume/messages

apigateway:
  host: https://cenlots-api.cloit.dev:${server.port}
