spring:
  security:
    user:
      name: admin
      password: admin

# 2시간(7,200,000), 1일(86,400,000) jwt token
token:
  expiration_time: 7200000
  refresh_time: 86400000
  secret: 'token_secret'

# eureka 가 포함되면 eureka server 도 등록되므로 해제한다.
eureka:
  instance:
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/

# file attach location - messages{lang}.properties 도 이 경로에 위치한다.
file:
  directory: ${app.home:${user.home}}/msa-attach-volume # url 사용시에는 사용되지 않는다
  url: http://${file.hostname:localhost}:8080 # nginx 로 파일 다운로드 처리
messages:
  directory: ${file.directory}/messages

apigateway:
  host: http://${apigateway.hostname:localhost}:${server.port}

# rabbitmq server
spring:
  rabbitmq:
    host: ${rabbitmq.hostname:localhost}
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://${zipkin.hostname:localhost}:${zipkin.port:9411}

egov:
  message: hello
