# 2시간(7,200,000), 1일(86,400,000) jwt token
token:
  expiration_time: 7200000
  refresh_time: 86400000
#  secret: 'token_secret'
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${spring.application.name}:${server.port} # spring Eureka에 등록되는 status 값
#instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # random port 사용시 eureka server에 인스턴스가 각각 표시되지 않는다
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka/

# file attach location - messages{lang}.properties 도 이 경로에 위치한다.
file:
  directory: ${app.home:${user.home}}/msa-attach-volume # url 사용시에는 사용되지 않는다
  url: http://${file.hostname:localhost}:8080 # nginx 로 파일 다운로드 처리
messages:
  directory: test   # ${file.directory}/messages

apigateway:
  host: http://${apigateway.hostname:localhost}:${server.port}

# rabbitmq server
spring:
  rabbitmq:
    host: ${rabbitmq.hostname:localhost}
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://${zipkin.hostname:localhost}:${zipkin.port:9411}

egov:
  message: hello
