database:
url: jdbc:postgresql://localhost:5432/msaportal
#  url: jdbc:mysql://${mysql.hostname:localhost}:3306/msaportal

spring:
  datasource:
    url: ${database.url}?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select 1
#    username: msaportal
#    password: msaportal
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      bindings:
        attachmentEntity-out-0: # 첨부파일 entity 정보 업데이트 하기 위한 이벤트
          destination: attachment-entity.topic # queue name
          group: attachment
