
server:
  port: 8050

spring:
  application:
    name: game-powerball-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: local
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
      fail-fast: true
  security:
    user:
      name: admin
      password: admin
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6666
    host: localhost

jdbc:
  #url: jdbc:log4jdbc:postgresql://10.10.5.183:5432/cenlotsdb01?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  url: jdbc:log4jdbc:postgresql://localhost:7777/cenlotsdb01?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenadm01
  password: cenlotaws123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5                #circuit Breaker가 열리기 전의 슬라이딩 윈도우 크기 (여기서는 5번의 호출)
        failureRateThreshold: 50            #실패율 임계값 (여기서는 50%).
        waitDurationInOpenState: 10s      #Circuit Breaker가 열린 상태에서 닫힌 상태로 돌아가기 전까지 대기하는 시간 (여기서는 10초).
        permittedNumberOfCallsInHalfOpenState: 3    #반열림 상태에서 허용되는 호출 수
        minimumNumberOfCalls: 5
        recordExceptions:
            - org.springframework.web.client.HttpServerErrorException
            - java.util.concurrent.TimeoutException
            - java.io.IOException
 #       ignoreExceptions:
 #           - io.github.robwin.exception.BusinessException
    shared:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 30
        waitDurationInOpenState: 3s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
            - io.github.robwin.exception.BusinessException
    instances:
      reqMngTcktSusValidateApiCircuitBreaker:
        baseConfig: default

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
  health-check:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions
        exclude: threaddump,heapdump
