server:
  port: 6030

spring:
  application:
    name: game-mng-service
  main:
    allow-bean-definition-overriding: true
    
jdbc:
  url: jdbc:log4jdbc:postgresql://localhost:7777/cenlotsdb02?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenadm02
  password: cenlotaws123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
