server:
  port: 7010

spring:
  application:
    name: game-mng-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: local
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
      fail-fast: true
  security:
    user:
      name: admin
      password: admin
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6666
    host: localhost

jdbc:
#  url: jdbc:postgresql://10.10.5.183:5432/cenausdb03?charSet=UTF-8&prepareThreshold=1
  url: jdbc:log4jdbc:postgresql://localhost:7777/cenlotsdb02?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenadm02
  password: cenlotaws123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#  driverClassName: org.postgresql.Driver

eureka:
  instance:
    prefer-ip-address: true
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/

logging:
  level:
    jdbc: off
      sqlonly: off
      sqltiming: off
      resultsettable: off
      resultset: off
      audit: off
      connection: off
    org:
	  mybatis: off
    org:
	  apache:
	    ibatis: off
