server:
  port: 9011

spring:
  application:
    name: lotuser-service
  profiles:
    active:
      on-profile: local
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6666
    host: localhost
  main:
    allow-bean-definition-overriding: true

  # oauth2 를 사용하기 위해서는 아래의 TODO 를 등록해야 함
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6c1a559189b320e2b1c6ede7c5506c01 # TODO https://developers.kakao.com/product/kakaoLogin
            client-secret: 8NxjNcruMpXQeje7RRWMAXCUN6z7qQgf # TODO
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


jdbc:
  url: jdbc:log4jdbc:postgresql://localhost:7777/cenlotsdb02?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenadm02
  password: cenlotaws123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: update
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  cache:
    jcache:
      config: classpath:ehcache.xml

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  health:
    mail:
      enabled: false

info:
  app:
    name: User Service
    description: 로그인, 회원관리 및 관리자 기능을 제공

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0

messages:
  directory: test

eureka:
  instance:
    prefer-ip-address: true
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
  
