server:
  port: 8080

spring:
  application:
    name: user-service
  profiles:
    active:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 16379
    host: dev-elasticache-replication-group.ikmdkh.ng.0001.apn2.cache.amazonaws.com

#  cloud:
#    config:
#      enabled: true
#      bootstrap.enabled: true
  main:
    allow-bean-definition-overriding: true

  # oauth2 를 사용하기 위해서는 아래의 TODO 를 등록해야 함
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6c1a559189b320e2b1c6ede7c5506c01 # TODO https://developers.kakao.com/product/kakaoLogin
            client-secret: 8NxjNcruMpXQeje7RRWMAXCUN6z7qQgf # TODO
            redirect-uri: https://cenlots-api.cloit.dev/oauth2/callback/kakao
##            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jdbc:
#  url: jdbc:postgresql://10.10.5.183:5432/cenausdb03?charSet=UTF-8&prepareThreshold=1
  url: jdbc:log4jdbc:postgresql://10.10.5.183:5432/cenlotsdb03?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenadm03
  password: cenlotaws123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#  driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: update
        format_sql: true
#        default_batch_fetch_size: 1000
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  cache:
    jcache:
      config: classpath:ehcache.xml

# rabbitmq server
#  rabbitmq:
#    host: ${rabbitmq.hostname:localhost}
#    port: 5672
#    username: guest
#    password: guest

#jwt:
#  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  health:
    mail:
      enabled: false

info:
  app:
    name: User Service
    description: 로그인, 회원관리 및 관리자 기능을 제공

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0

messages:
  directory: test

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: cenlots2024-discoveryserver-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
