database:
  url: jdbc:postgresql://localhost:5432/msaportal
#  url: jdbc:mysql://${mysql.hostname:localhost}:3306/msaportal

#spring:   #mysql
#  datasource:
#    url: ${database.url}?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select 1
#    username: user02   # msaportal
#    password: Abcd123@ # msaportal
#    driver-class-name: com.mysql.cj.jdbc.Driver
#jdbc:
#  url: jdbc:postgresql://localhost:5432/msaportal
#  username: postgres
#  password: user1234
#  driverClassName: org.postgresql.Driver

jdbc:
#  url: jdbc:postgresql://10.10.5.183:5432/cenausdb03?charSet=UTF-8&prepareThreshold=1
  url: jdbc:log4jdbc:postgresql://localhost:7777/cenlotsdb03?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: cenadm03
  password: cenlotaws123!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#  driverClassName: org.postgresql.Driver

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6c1a559189b320e2b1c6ede7c5506c01 # TODO https://developers.kakao.com/product/kakaoLogin
            client-secret: 8NxjNcruMpXQeje7RRWMAXCUN6z7qQgf # TODO
            redirect-uri: http://localhost:8000/oauth2/callback/kakao
##            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  mail: # 비밀번호 변경 이메일 발송
    host: smtp.gmail.com # smtp host
    port: 587 # smtp port
    username: email_username # 계정
    password: 'email_password' # 비밀번호 - 구글 보안 2단계 인증 해제, 보안 수준이 낮은 앱의 액세스 허용(https://myaccount.google.com/lesssecureapps)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
